image: docker

services:
  - docker:dind

stages:
  - deploy

step-deploy-prod:
  stage: deploy
  script:
    - sudo touch acme.json && sudo chmod 600 acme.json
    - docker stack deploy -c docker-compose.yml traefik
  environment: production
