name: Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: self-hosted
    environment: 
      name: production
      url: http://vca.ifba.edu.br:81/proxy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Destroy docker
      run: bash ./destroy.sh
      id: docker_destroy
    - name: Docker deploy
      env:
        EMAIL: ${{ secrets.EMAIL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        bash ./deploy.sh
      id: docker_deploy
