name: Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: self-hosted
    environment: 
      name: production
      url: "${{ vars.PROTOCOL }}://${{ vars.DOMAIN }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker deploy
      env:
        EMAIL: ${{ vars.EMAIL }}
        DOMAIN: ${{ vars.DOMAIN }}
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        PROTOCOL: ${{ vars.PROTOCOL }}
      run: |
        bash ./deploy.sh
      id: docker_deploy
    - name: Check on failures
      id: docker_check
      run: |
        if [ $(docker stack services infra | grep infra >/dev/null ; echo $?) -eq "1" ]
          then
            echo "Falha no deploy da aplicação, tente novamente."
            exit 1
        fi
