name: Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: self-hosted
    environment: 
      name: production
      url: https://vca.ifba.edu.br
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Destroy docker
      run: bash ./destroy.sh
      id: docker_destroy
    - name: Docker deploy
      env:
        EMAIL: ${{ secrets.EMAIL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        PROTOCOL: ${{ secrets.PROTOCOL }}
      run: |
        bash ./deploy.sh
      id: docker_deploy
    - name: Check on failures
      if: ${{$(docker stack services infra | grep infra >/dev/null ; echo $?) -eq "1")}}
      run: exit 1
